services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=JZVdfKrmEltrZmwCpSVQ
      - POSTGRES_DB=learning
    ports:
      - "5432:5432"
    volumes:
      - ./data/db/:/var/lib/postgresql/data/
    restart: always

  redis:
    image: redis:8.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis/:/data/
    command: redis-server --appendonly yes --save "60 1" --loglevel warning
    restart: always