services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=JZVdfKrmEltrZmwCpSVQ
      - POSTGRES_DB=learning
    ports:
      - "5432:5432"
    volumes:
      - ./data/db/:/var/lib/postgresql/data/