server:
  port: 8080
databasepostgres:
  host: localhost
  port: 5432
  dbname: learning
  username: postgres
  password: JZVdfKrmEltrZmwCpSVQ
  sslmode: disable
redis:
  host: localhost
  port: 6379
jwt:
  secretkey: example_jwt_secret_key